user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

tvdb:
    resource: "@TVDBBundle/Controller/"
    type:     annotation
    prefix:   /kittyadmin/tvdb

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /kittyadmin

serie:
    resource: "@SerieBundle/Controller/"
    type:     annotation
    prefix:   /serie

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"