user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

tvdb:
    resource: "@TVDBBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

serie:
    resource: "@SerieBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
